misalignment: [0.998953, 0.0904525, -0.0393657, 
	-0.0290644, 0.996407, 0.0130686, 
	0.0462864, -0.00174331, 0.999152]
scale: [9.33844, 0, 0, 
	0, 8.80029, 0, 
	0, 0, 9.22352]
bias: [0.00460391, -0.0259168, -0.0020273]

# ---- Folded calibration (T = R * M * S) ----
# T (misalignment * scale):
#   9.32866410   0.79600809  -0.36309026
#  -0.27141602   8.76866627   0.12053828
#   0.43224238  -0.01534159   9.21569149
# R (rotation):
#   0.99733108   0.05914185  -0.04281300
#  -0.05878506   0.99822502   0.00954637
#   0.04330160  -0.00700413   0.99903749
# S (folded scale):
#   9.33843866   0.00000000   0.00000000
#   0.00000000   8.80028688   0.00000000
#   0.00000000   0.00000000   9.22351702
# M (folded misalignment):
#   1.00000000   0.03156178   0.00323598
#   0.02974295   1.00000000   0.00371904
#   0.00319616   0.00389790   1.00000000
# T reconstructed (R * M * S):
#   9.32866410   0.79600809  -0.36309026
#  -0.27141602   8.76866627   0.12053828
#   0.43224238  -0.01534159   9.21569149
# Recon error: 5.72196e-17
