misalignment: [1, -0.00545714, -0.00257778, 
	0, 1, -0.00177375, 
	-0, 0, 1]
scale: [9.81391, 0, 0, 
	0, 9.82191, 0, 
	0, 0, 9.83378]
bias: [-0.00439003, -0.00125807, -0.00966606]

# ---- Folded calibration (T = R * M * S) ----
# T (misalignment * scale):
#   9.81391031  -0.05359950  -0.02534929
#   0.00000000   9.82190596  -0.01744271
#   0.00000000   0.00000000   9.83377555
# R (rotation):
#   0.99999544  -0.00273024  -0.00129140
#   0.00272909   0.99999588  -0.00088917
#   0.00129382   0.00088565   0.99999877
# S (folded scale):
#   9.81386555   0.00000000   0.00000000
#   0.00000000   9.82201184   0.00000000
#   0.00000000   0.00000000   9.83381171
# M (folded misalignment):
#   1.00000000  -0.00272799  -0.00128878
#  -0.00273025   1.00000000  -0.00088106
#  -0.00129140  -0.00088212   1.00000000
# T reconstructed (R * M * S):
#   9.81391031  -0.05359950  -0.02534929
#   0.00000000   9.82190596  -0.01744271
#   0.00000000  -0.00000000   9.83377555
# Recon error: 1.3917e-17
