misalignment: [0.999522, -0.0057849, -0.0302043, 
	-0.0120781, 0.999943, 0.0137538, 
	0.0298861, -0.0127846, 0.999449]
scale: [9.50422, 0, 0, 
	0, 9.6112, 0, 
	0, 0, 9.71389]
bias: [0.0053882, -0.011212, -0.0029089]

# ---- Folded calibration (T = R * M * S) ----
# T (misalignment * scale):
#   9.49967945  -0.05559984  -0.29340136
#  -0.11479318   9.61065258   0.13360271
#   0.28404425  -0.12287571   9.70854380
# R (rotation):
#   0.99954541   0.00329798  -0.02996837
#  -0.00290395   0.99990889   0.01318220
#   0.03000911  -0.01308918   0.99946392
# S (folded scale):
#   9.50421823   0.00000000   0.00000000
#   0.00000000   9.61120196   0.00000000
#   0.00000000   0.00000000   9.71389318
# M (folded misalignment):
#   1.00000000  -0.00906971  -0.00023792
#  -0.00917181   1.00000000   0.00057093
#  -0.00024317   0.00057703   1.00000000
# T reconstructed (R * M * S):
#   9.49967945  -0.05559984  -0.29340136
#  -0.11479318   9.61065258   0.13360271
#   0.28404425  -0.12287571   9.70854380
# Recon error: 6.93889e-18
