misalignment: [0.99559, -0.0229529, 0.00147314, 
	0.101743, 1.00115, 0.0939249, 
	0.00697168, -0.0138913, 0.996477]
# scale: [0.641527, 0, 0, 
# 	0, 0.638467, 0, 
# 	0, 0, 0.591133]
#bias: [-0.000321213, -0.000130388, 2.85902e-05]

# ---- Folded calibration (T = R * M * S) ----
# T (misalignment * scale):
#   0.63869745  -0.01465464   0.00087082
#   0.06527095   0.63920205   0.05552204
#   0.00447252  -0.00886916   0.58904994
# R (rotation):
#   0.99805971  -0.06210544  -0.00444275
#   0.06225271   0.99670044   0.05208484
#   0.00119334  -0.05226035   0.99863278
# S (folded scale):
#   0.64152682   0.00000000   0.00000000
#   0.00000000   0.63846661   0.00000000
#   0.00000000   0.00000000   0.59113257
# M (folded misalignment):
#   1.00000000   0.03939950   0.00850649
#   0.03921156   1.00000000   0.04144723
#   0.00783827   0.03837445   1.00000000
# T reconstructed (R * M * S):
#   0.63869745  -0.01465464   0.00087082
#   0.06527095   0.63920205   0.05552204
#   0.00447252  -0.00886916   0.58904994
# Recon error: 0

scale: [1, 0, 0,
        0, 1, 0,
        0, 0, 1]

bias: [0.0, 0.0, 0.0]