misalignment: [1, 0.0297649, -0.00587199, 
	-0.0218949, 1, -8.49999e-05, 
	-0.0201913, -0.00724208, 1]
#scale: [0.797123, 0, 0, 
#0, 0.786505, 0, 
#0, 0, 0.787385]
scale: [1, 0, 0,
        0, 1, 0,
        0, 0, 1]
bias: [0.0, 0.0, 0.0]
#bias: [-0.000143807, -6.81364e-05, 0.00155113]
