misalignment: [1, -0.0569148, 0.0502866, 
	0.0635294, 1, -0.00814257, 
	0.0236534, 0.000539297, 1]
scale: [1, 0, 0, 
	0, 1, 0, 
	0, 0, 1]
bias: [0.0, 0.0, 0.0]
#bias: [-0.000104484, -3.18906e-05, -0.000310852]
